gage_id: "01591400"
start_date: "2015-06-05"
end_date: "2015-08-05"
training_start_date: "2015-07-05"
data_root: ~/ngiab_preprocess_output
norm: True
target_variables:
  streamflow:
    observed_data_path: "~/ngiab_preprocess_output/01591400_observed_flow_2015-06-15_2015-08-15.csv"
    weights: 0.7
  ET:
    observed_data_path: "daily/et_daily_mean_2016_2023.csv"
    weights: 0.3


algorithm: "DDS" #Available [DDS, NSGAII, SCE-UA]
objective_function: "KGE" #Available [KGE, RMSE]
repetitions: 10
dds_trials: 1  #used for DDS, if other algorithm usedm will be ignored
n_pop: 5  #used for NSGAII, if other algorithm used, will be ignored
execution_mode: "serial"
merge_catchment: False
