gage_id: "10109001"
start_date: "2016-06-05"
end_date: "2016-08-05"
training_start_date: "2016-07-05"
data_root: ~/ngiab_preprocess_output
algorithm: "DDS" #Available [DDS, SCE]
objective_function: "KGE" #Available [KGE, RMSE]
repetitions: 10
dds_trials: 1  #used for DDS, if other algorithm is used. otherwise, will be ignored.
execution_mode: "parallel"
merge_catchment: False